term="NovikovGE"
name="Novikov G.E."
work="Rosatom State Atomic Energy Corporation"
full_name="Novikov Grigory Evgenâ€™evich"
regals="Chief Specialist of Department, Secretary of the Metrology Concil"
email="genovikov@rosatom.ru"