term="RyazapovRR"
name="Ryazapov R.R."
work="Nizhny Novgorod State Technical University n.a. R.E. Alekseev."
full_name="Rayzapov Renat Ramilâ€™yevich"
regals="Assistant"
email="ryazapov.renat@gmail.com"